apiVersion: apps/v1 
kind: Deployment
metadata:
  name:  mongodb
  labels:
    app:  mongodb 
    tier: db 
    project: roboshop    
spec:
   replica: 1 
   selector: 
     matchLabels: 
      app: mangodb 
      tier: db 
      project: roboshop   
   template:  
     metadata:
      labels:
        app: mongodb 
        tier: db 
        project: roboshop 
    spec:
      containers:
      - name: mangodb
        image:  siraz123/mongodb:1.0.0
        