apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: cart
 namespace: roboshop
 labels: 
   app: cart 
   tier: app
   project: roboshop
spec:
 replicas: 1
 selector:
  matchLabels:
   app: cart 
   tier: app
   project: roboshop
 template: 
  metadata:
   labels: 
    app: cart 
    tier: app
    project: roboshop
  spec:
    containers:
      - name: cart
        image: siraz123/cart:1.0.0
        envFrom: 
        - configMapRef:
           name: cart  
---
apiVersion: v1 
kind: Service 
metadata: 
 name: cart
 namespace: roboshop
spec:
 selector:
    app: cart 
    tier: app
    project: roboshop
 ports: 
 - name: mongodb-port 
   protocol: TCP
   port: 8080
   targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: catalogue 
  CATALOGUE_PORT: "8080"





