apiVersion: apps/v1 
kind: Deployment 
metatdata: 
  name: redis
  namespace: roboshop 
  labels: 
    app: redis 
    tier: db 
    project: roboshop 
spec: 
  replicas: 1 
  selector: 
    matchLabels:
      app: redis 
      tier: db 
      project: roboshop 
  template: 
    metadata: 
      labels:
        app: redis 
        tier: db 
        project: roboshop
    spec: 
      containers:
        - name: redis 
          image: redis 
---
apiVersion: v1 
kind: Service 
metadata: 
   name: redis 
   namespace: roboshop
spec: 
   selector: 
     app: redis 
     tier: db 
     project: roboshop 
   ports: 
   - name: redis-port 
     protocol: TCP 
     port: 6379
     targetPort: 6379               